
package introsde.assignment3.soap.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "People", targetNamespace = "http://ws.soap.assignment3.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface People {


    /**
     * 
     * @param personId
     * @return
     *     returns introsde.assignment3.soap.ws.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "readPerson", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPerson")
    @ResponseWrapper(localName = "readPersonResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/readPersonRequest", output = "http://ws.soap.assignment3.introsde/People/readPersonResponse")
    public Person readPerson(
        @WebParam(name = "personId", targetNamespace = "")
        long personId);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.assignment3.soap.ws.Person>
     */
    @WebMethod
    @WebResult(name = "people", targetNamespace = "")
    @RequestWrapper(localName = "readPersonList", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonList")
    @ResponseWrapper(localName = "readPersonListResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonListResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/readPersonListRequest", output = "http://ws.soap.assignment3.introsde/People/readPersonListResponse")
    public List<Person> readPersonList();

    /**
     * 
     * @param personIn
     * @return
     *     returns introsde.assignment3.soap.ws.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.UpdatePersonResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/updatePersonRequest", output = "http://ws.soap.assignment3.introsde/People/updatePersonResponse")
    public Person updatePerson(
        @WebParam(name = "personIn", targetNamespace = "")
        Person personIn);

    /**
     * 
     * @param personIn
     * @return
     *     returns introsde.assignment3.soap.ws.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.CreatePersonResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/createPersonRequest", output = "http://ws.soap.assignment3.introsde/People/createPersonResponse")
    public Person createPerson(
        @WebParam(name = "personIn", targetNamespace = "")
        Person personIn);

    /**
     * 
     * @param personId
     */
    @WebMethod
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.DeletePersonResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/deletePersonRequest", output = "http://ws.soap.assignment3.introsde/People/deletePersonResponse")
    public void deletePerson(
        @WebParam(name = "personId", targetNamespace = "")
        long personId);

    /**
     * 
     * @param personId
     * @param type
     * @return
     *     returns java.util.List<introsde.assignment3.soap.ws.Activity>
     */
    @WebMethod
    @WebResult(name = "preferences", targetNamespace = "")
    @RequestWrapper(localName = "readPersonPreferences", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonPreferences")
    @ResponseWrapper(localName = "readPersonPreferencesResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonPreferencesResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/readPersonPreferencesRequest", output = "http://ws.soap.assignment3.introsde/People/readPersonPreferencesResponse")
    public List<Activity> readPersonPreferences(
        @WebParam(name = "personId", targetNamespace = "")
        long personId,
        @WebParam(name = "type", targetNamespace = "")
        String type);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.assignment3.soap.ws.Activity>
     */
    @WebMethod
    @WebResult(name = "preferences", targetNamespace = "")
    @RequestWrapper(localName = "readPreferences", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPreferences")
    @ResponseWrapper(localName = "readPreferencesResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPreferencesResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/readPreferencesRequest", output = "http://ws.soap.assignment3.introsde/People/readPreferencesResponse")
    public List<Activity> readPreferences();

    /**
     * 
     * @param activityId
     * @param personId
     * @return
     *     returns introsde.assignment3.soap.ws.Activity
     */
    @WebMethod
    @WebResult(name = "preference", targetNamespace = "")
    @RequestWrapper(localName = "readPersonPreferences2", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonPreferences2")
    @ResponseWrapper(localName = "readPersonPreferences2Response", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.ReadPersonPreferences2Response")
    @Action(input = "http://ws.soap.assignment3.introsde/People/readPersonPreferences2Request", output = "http://ws.soap.assignment3.introsde/People/readPersonPreferences2Response")
    public Activity readPersonPreferences2(
        @WebParam(name = "personId", targetNamespace = "")
        long personId,
        @WebParam(name = "activityId", targetNamespace = "")
        long activityId);

    /**
     * 
     * @param activity
     * @param personId
     */
    @WebMethod
    @RequestWrapper(localName = "savePersonPreferences", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.SavePersonPreferences")
    @ResponseWrapper(localName = "savePersonPreferencesResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.SavePersonPreferencesResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/savePersonPreferencesRequest", output = "http://ws.soap.assignment3.introsde/People/savePersonPreferencesResponse")
    public void savePersonPreferences(
        @WebParam(name = "personId", targetNamespace = "")
        long personId,
        @WebParam(name = "activity", targetNamespace = "")
        Activity activity);

    /**
     * 
     * @param activity
     * @param personId
     * @return
     *     returns introsde.assignment3.soap.ws.Activity
     */
    @WebMethod
    @WebResult(name = "preference", targetNamespace = "")
    @RequestWrapper(localName = "updatePersonPreferences", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.UpdatePersonPreferences")
    @ResponseWrapper(localName = "updatePersonPreferencesResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.UpdatePersonPreferencesResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/updatePersonPreferencesRequest", output = "http://ws.soap.assignment3.introsde/People/updatePersonPreferencesResponse")
    public Activity updatePersonPreferences(
        @WebParam(name = "personId", targetNamespace = "")
        long personId,
        @WebParam(name = "activity", targetNamespace = "")
        Activity activity);

    /**
     * 
     * @param activity
     * @param personId
     * @param value
     * @return
     *     returns introsde.assignment3.soap.ws.Activity
     */
    @WebMethod
    @WebResult(name = "preference", targetNamespace = "")
    @RequestWrapper(localName = "evaluatePersonPreferences", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.EvaluatePersonPreferences")
    @ResponseWrapper(localName = "evaluatePersonPreferencesResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.EvaluatePersonPreferencesResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/evaluatePersonPreferencesRequest", output = "http://ws.soap.assignment3.introsde/People/evaluatePersonPreferencesResponse")
    public Activity evaluatePersonPreferences(
        @WebParam(name = "personId", targetNamespace = "")
        long personId,
        @WebParam(name = "activity", targetNamespace = "")
        Activity activity,
        @WebParam(name = "value", targetNamespace = "")
        int value);

    /**
     * 
     * @param personId
     * @return
     *     returns java.util.List<introsde.assignment3.soap.ws.Activity>
     */
    @WebMethod
    @WebResult(name = "preferences", targetNamespace = "")
    @RequestWrapper(localName = "getBestPersonPreferences", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.GetBestPersonPreferences")
    @ResponseWrapper(localName = "getBestPersonPreferencesResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.GetBestPersonPreferencesResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/getBestPersonPreferencesRequest", output = "http://ws.soap.assignment3.introsde/People/getBestPersonPreferencesResponse")
    public List<Activity> getBestPersonPreferences(
        @WebParam(name = "personId", targetNamespace = "")
        long personId);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://ws.soap.assignment3.introsde/", className = "introsde.assignment3.soap.ws.InitResponse")
    @Action(input = "http://ws.soap.assignment3.introsde/People/initRequest", output = "http://ws.soap.assignment3.introsde/People/initResponse")
    public void init();

}
